export default function Legal(){return <main className="legal-page">
  <header><a href="/inspire">ART STUDIO INSPIRE</a><nav><a href="/inspire">STUDIJA</a><a href="/inspire#kontakti">KONTAKTI</a></nav></header>
  <section className="legal-hero"><p>STUDIO POLICIES</p><h1>Clear terms,<br/><em>so you can make plans.</em></h1><div><span>ARTWORK · CLASSES · PRIVATE SESSIONS</span><span>LAST REVIEWED · PRE-LAUNCH DRAFT</span></div></section>
  <section className="legal-grid">
    <article><span>01</span><h2>Original artwork</h2><p>Every listed painting is a unique original. A work is only secured when payment has completed successfully. Colours can differ slightly between a screen and the original artwork.</p><p>Artwork dimensions, condition and availability are confirmed on the artwork page or directly by email before purchase.</p></article>
    <article><span>02</span><h2>Shipping</h2><p>Shipping is charged according to the delivery region: Latvia, the EU, or international. Packaging, courier selection and dispatch timing are confirmed by email after purchase.</p><p>Customs charges and import taxes outside the EU are the buyer’s responsibility.</p></article>
    <article><span>03</span><h2>Classes & bookings</h2><p>A paid class or private session is reserved only after confirmed payment. The studio may contact you if a practical detail needs to change, and will always offer a comparable alternative or a refund.</p><p>Class details and what to bring are sent by email after a booking is confirmed.</p></article>
    <article><span>04</span><h2>Cancellations & refunds</h2><p>Bookings can be cancelled or rescheduled up to 24 hours before their start time for a full refund. Cancellations after that point may not be refundable because the place has been held for you.</p><p>For artwork issues, contact the studio promptly with photographs so a fair resolution can be arranged.</p></article>
    <article><span>05</span><h2>Payments & invoices</h2><p>Payments are processed securely by Stripe. Stripe may send a payment receipt after checkout. Choose the business/VAT invoice option at checkout when you need company billing details recorded.</p></article>
    <article><span>06</span><h2>Privacy & cookies</h2><p>The studio uses the details you provide to process an order or booking, communicate about it, and meet legal record-keeping obligations. Payment card data is handled by Stripe, not stored by this site.</p><p>This draft site currently uses only necessary technical cookies. Any analytics or marketing cookies will be disclosed here before launch.</p></article>
  </section>
  <section className="legal-help"><p>QUESTIONS ABOUT A POLICY?</p><h2>Write before you buy or book.<br/><em>We are happy to clarify.</em></h2><a href="mailto:misscoookiez@gmail.com">misscoookiez@gmail.com →</a></section>
  <footer>© SANDRA RUDZĪTE · RIGA, LATVIA <span>This policy needs final business and VAT details before taking live payments.</span></footer>
</main>}
