"use client";
import { useEffect, useState } from "react";
import { artwork, classes, privateSlots, ui } from "@/lib/catalog";

const eur = new Intl.NumberFormat("en-IE", { style:"currency", currency:"EUR", maximumFractionDigits:0 });

export default function StudioApp() {
  const [lang,setLang]=useState("en"), [page,setPage]=useState("home"), [cart,setCart]=useState([]), [modal,setModal]=useState(null);
  const [payment,setPayment]=useState("");
  useEffect(()=>{if(new URLSearchParams(window.location.search).get("payment")==="success")setPayment("Thank you — your payment flow was completed in demo mode. No card was charged.");},[]);
  const t=ui[lang]; const go=(next)=>{setPage(next);setModal(null);window.scrollTo({top:0,behavior:"smooth"});};
  const add=(item)=>{setCart(c=>c.find(x=>x.id===item.id)?c:[...c,item]);setModal("cart");};
  return <><Header t={t} lang={lang} setLang={setLang} page={page} go={go} cart={cart} open={()=>setModal("cart")}/>
    <main className="shell">{payment&&<div className="payment-banner">{payment}<button onClick={()=>setPayment("")}>×</button></div>}{page==="home"&&<Home t={t} lang={lang} go={go} openArtwork={(a)=>setModal({type:"art",item:a})}/>} {page==="shop"&&<Shop t={t} lang={lang} openArtwork={(a)=>setModal({type:"art",item:a})}/>} {page==="classes"&&<Classes t={t} lang={lang} book={(item)=>setModal({type:"booking",item,kind:"class"})}/>} {page==="private"&&<Private t={t} lang={lang} book={()=>setModal({type:"booking",kind:"private"})}/>} {page==="about"&&<About t={t}/>}</main>
    <Footer/><Modal modal={modal} t={t} lang={lang} cart={cart} add={add} remove={(id)=>setCart(c=>c.filter(x=>x.id!==id))} close={()=>setModal(null)}/></>;
}
function Header({t,lang,setLang,page,go,cart,open}) { return <header className="site-header shell"><a className="brand" onClick={()=>go("home")}>Sandra Rudzīte</a><nav className="nav"><a onClick={()=>go("shop")}>{t.shop}</a><a onClick={()=>go("classes")}>{t.classes}</a><a onClick={()=>go("private")}>{t.private}</a><a onClick={()=>go("about")}>{t.about}</a><button className="lang" onClick={()=>setLang(lang==="en"?"lv":"en")}>{lang==="en"?"LV":"EN"}</button><a className="show-mobile" onClick={open}>{t.cart} <b className="cart-count">{cart.length}</b></a></nav></header>; }
function Home({t,lang,go,openArtwork}) {return <><section className="hero"><div className="hero-copy"><div className="eyebrow">{t.heroEyebrow}</div><h1>{t.hero}</h1><p className="lead">{t.heroBody}</p><button className="button" onClick={()=>go("shop")}>{t.viewWork}</button></div><div><div className="hero-art"><img src="/art/twilight.jpg" alt="Twilight painting"/></div><div className="caption"><span>Twilight</span><span>oil on canvas</span></div></div></section><section className="section"><div className="section-head"><div><div className="eyebrow">{t.portfolio}</div><h2>{t.latest}</h2><p>{t.latestSub}</p></div><a className="section-link" onClick={()=>go("shop")}>{t.viewAll} →</a></div><ArtworkGrid lang={lang} onOpen={openArtwork}/></section><section className="section split"><article className="panel dark"><div><div className="eyebrow">{t.classes}</div><h2>{t.learn}</h2><p>{t.classesBody}</p></div><button className="button alt" onClick={()=>go("classes")}>{t.seeClasses}</button></article><article className="panel"><div><div className="eyebrow">{t.private}</div><h2>{t.privateTitle}</h2><p>{t.privateBody}</p></div><button className="button alt" onClick={()=>go("private")}>{t.book}</button></article></section></>}
function ArtworkGrid({lang,onOpen}) {return <div className="grid">{artwork.map(a=><button className="art-card" key={a.id} onClick={()=>onOpen(a)} style={{border:0,background:"none",padding:0,textAlign:"left"}}><div className="art-image"><img src={a.image} alt={a.title}/></div><div className="art-info"><div>{lang==="lv"?a.titleLv:a.title}<br/><span>{a.medium}, {a.size}</span></div><b>{eur.format(a.price)}</b></div></button>)}</div>}
function Shop({t,lang,openArtwork}) {return <section className="page"><div className="page-intro"><div className="eyebrow">{t.portfolio} / {t.shop}</div><h1>{t.introShop}</h1><p>{t.shipping}. Each painting is an original and available only once.</p></div><ArtworkGrid lang={lang} onOpen={openArtwork}/></section>}
function Classes({t,lang,book}) {return <section className="page"><div className="page-intro"><div className="eyebrow">Inspire art studio / Riga</div><h1>{t.introClasses}</h1><p>{t.fullPayment}</p></div><div className="split" style={{marginBottom:36}}><img className="studio-photo" src="/art/studio-session.jpeg" alt="Student painting in the Inspire art studio"/><article className="panel dark"><div><div className="eyebrow">What to expect</div><h3>Make it yours.</h3><p>Small groups, materials guidance and space to paint at your own pace. Suitable for beginners and returning students.</p></div></article></div><div className="booking-grid">{classes.map(c=><article className="booking-card" key={c.id}><div className="date">{c.date} · {c.time}</div><h3>{lang==="lv"?c.titleLv:c.title}</h3><p>{c.level}<br/>{c.seats} {t.available}</p><b>{eur.format(c.price)}</b><button className="button" onClick={()=>book(c)}>{t.reserve}</button></article>)}</div></section>}
function Private({t,book}) {return <section className="page"><div className="split"><div className="page-intro"><div className="eyebrow">Riga studio</div><h1>{t.introPrivate}</h1><p>One-to-one tuition for drawing, oil painting, portfolio guidance or a focused creative reset. Bring your own idea or start from a blank page.</p><p>{t.fullPayment}</p></div><article className="panel dark"><div><div className="eyebrow">90 minutes · €75</div><h2>{t.privateTitle}</h2><p>Weekday and weekend times are released monthly.</p></div><button className="button alt" onClick={book}>{t.schedule}</button></article></div></section>}
function About({t}) {return <section className="page"><div className="page-intro"><div className="eyebrow">{t.about}</div><h1>About the artist</h1><p>I am Sandra Rudzīte, a traditional artist based in Latvia. My work explores the intimacy of shadow, memory and the changing emotional weight of ordinary places.</p><p>Alongside my studio practice, I teach small, generous classes for people who want to develop their eye and make work with confidence.</p></div></section>}
function Footer(){return <footer className="footer shell"><span>© Sandra Rudzīte</span><span>Riga, Latvia · Instagram · Contact</span><span>Privacy · Terms · Shipping & refunds</span></footer>}
function Modal({modal,t,lang,cart,add,remove,close}) {if(!modal)return null; if(modal==="cart") return <Overlay close={close}><h3>{t.cart}</h3>{cart.length?<><div className="facts">{cart.map(x=><div key={x.id}><span>{lang==="lv"?x.titleLv:x.title}</span><span>{eur.format(x.price)} <button onClick={()=>remove(x.id)} style={{border:0,background:"none",color:"var(--rust)"}}>×</button></span></div>)}</div><CheckoutButton t={t} cart={cart}/></>:<p className="lead">Your cart is empty.</p>}</Overlay>; if(modal.type==="art"){const a=modal.item;return <Overlay close={close}><div className="detail-art image-detail" style={{minHeight:250}}><img src={a.image} alt={a.title}/></div><h3 style={{marginTop:20}}>{lang==="lv"?a.titleLv:a.title}</h3><p className="price">{eur.format(a.price)}</p><p>{a.description}</p><div className="facts"><div><span>{a.medium}</span><span>{a.size}</span></div></div><button className="button" onClick={()=>add(a)}>{t.add}</button></Overlay>}return <BookingForm item={modal.item} kind={modal.kind} t={t} close={close}/>}
function Overlay({children,close}){return <div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button>{children}</div></div>}
function CheckoutButton({t,cart}){const [state,setState]=useState("");async function checkout(){setState("Opening secure checkout…");const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"art",items:cart,invoice:false})});const data=await r.json();if(data.url)location.href=data.url;else setState(data.error||"Checkout is not configured yet.")}return <><button className="button" onClick={checkout}>{t.checkout}</button><div className="status">{state}</div></>}
function BookingForm({item,kind,t,close}){const [state,setState]=useState("");async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);setState("Holding your place…");const payload={kind,itemId:item?.id,privateSlot:f.get("slot"),name:f.get("name"),email:f.get("email"),invoice:f.get("invoice")==="on"};const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(d.url)location.href=d.url;else setState(d.error||"Booking checkout is not configured yet.")}return <Overlay close={close}><div className="eyebrow">{kind==="class"?t.classes:t.private}</div><h3>{item?item.title:"Private studio session"}</h3><p className="note">{t.fullPayment}</p><form onSubmit={submit}><input required name="name" className="field" placeholder={t.name}/><input required type="email" name="email" placeholder={t.email}/>{kind==="private"&&<select name="slot" required className="field"><option value="">{t.selectSlot}</option>{privateSlots.map(slot=><option value={slot.id} key={slot.id}>{slot.label}</option>)}</select>}<label style={{display:"flex",gap:8,margin:"5px 0 18px"}}><input type="checkbox" name="invoice"/>{t.invoice}</label><button className="button">{t.proceed}</button><div className="status">{state}</div></form></Overlay>}
