export const artwork = [
  { id:"twilight", title:"Twilight", titleLv:"Krēsla", medium:"Oil on canvas", size:"Details to be confirmed", price:850, image:"/art/twilight.jpg", description:"A nocturnal landscape in oil. Final title, dimensions and price can be edited in the studio dashboard." },
  { id:"crow", title:"Crow", titleLv:"Vārna", medium:"Oil on canvas", size:"Details to be confirmed", price:720, image:"/art/crow.jpg", description:"An original blue-black study. Final title, dimensions and price can be edited in the studio dashboard." },
  { id:"still-life-horse", title:"Still Life with Horse", titleLv:"Klusā daba ar zirgu", medium:"Oil on canvas", size:"Details to be confirmed", price:480, image:"/art/still-life-horse.jpg", description:"An original still life. Final title, dimensions and price can be edited in the studio dashboard." }
];

export const classes = [
  { id:"00000000-0000-4000-8001-000000000001", date:"Sat, 5 Sep", title:"Youth painting group", titleLv:"Jauniešu gleznošanas grupa", time:"11:00–13:00", price:25, seats:7, level:"Ages 8–16" },
  { id:"00000000-0000-4000-8001-000000000002", date:"Sat, 5 Sep", title:"Adult painting group", titleLv:"Pieaugušo gleznošanas grupa", time:"14:00–16:00", price:25, seats:7, level:"All levels" },
  { id:"00000000-0000-4000-8001-000000000003", date:"Sun, 6 Sep", title:"Mixed painting group", titleLv:"Jaukta gleznošanas grupa", time:"11:00–13:00", price:25, seats:7, level:"All levels" },
  { id:"00000000-0000-4000-8001-000000000004", date:"Sun, 6 Sep", title:"Mixed painting group", titleLv:"Jaukta gleznošanas grupa", time:"14:00–16:00", price:25, seats:7, level:"All levels" },
  { id:"00000000-0000-4000-8001-000000000005", date:"Thu, 10 Sep", title:"Youth painting group", titleLv:"Jauniešu gleznošanas grupa", time:"16:00–18:00", price:25, seats:7, level:"Ages 8–16" },
  { id:"00000000-0000-4000-8001-000000000006", date:"Thu, 10 Sep", title:"Adult painting group", titleLv:"Pieaugušo gleznošanas grupa", time:"18:30–20:30", price:25, seats:7, level:"All levels" }
];

export const privateSlots = [
  { id:"00000000-0000-4000-8000-000000000201", label:"Mon 21 Sep · 17:00" },
  { id:"00000000-0000-4000-8000-000000000202", label:"Wed 23 Sep · 11:00" },
  { id:"00000000-0000-4000-8000-000000000203", label:"Sat 26 Sep · 15:00" }
];

export const ui = {
  en: { shop:"Shop originals", portfolio:"Portfolio", classes:"Classes", private:"Private sessions", about:"About", cart:"Cart", heroEyebrow:"Traditional artist · Riga, Latvia", hero:"Painting the quiet places between light and shadow.", heroBody:"Original paintings, intimate studio classes and personal creative sessions.", viewWork:"View work", latest:"Selected originals", latestSub:"Every work is one of one.", viewAll:"View all", learn:"Learn in the studio", classesBody:"Small, hands-on art classes for curious beginners and practicing artists.", seeClasses:"See classes", privateTitle:"A session shaped around you", privateBody:"Book a focused, one-to-one drawing or painting session in my Riga studio.", book:"Book a private session", available:"places available", reserve:"Reserve a place", sold:"Sold", add:"Add to cart", shipping:"Shipping is calculated at checkout", home:"Home", contact:"Contact", checkout:"Checkout", schedule:"Choose a time", introShop:"Original artwork", introClasses:"Classes in the studio", introPrivate:"Private sessions", invoice:"I need a business/VAT invoice", fullPayment:"Full payment reserves your place. Cancel 24+ hours before for an automatic refund.", name:"Name", email:"Email", message:"Message", selectSlot:"Select a session", proceed:"Continue to secure payment" },
  lv: { shop:"Oriģināldarbi", portfolio:"Portfolio", classes:"Nodarbības", private:"Privātās nodarbības", about:"Par mani", cart:"Grozs", heroEyebrow:"Māksliniece · Rīga, Latvija", hero:"Gleznojot kluso telpu starp gaismu un ēnu.", heroBody:"Oriģinālgleznas, radošās nodarbības un personīgas sesijas studijā.", viewWork:"Skatīt darbus", latest:"Izvēlētie oriģināldarbi", latestSub:"Katrs darbs ir vienīgais eksemplārs.", viewAll:"Skatīt visu", learn:"Mācies studijā", classesBody:"Mazas, praktiskas mākslas nodarbības ziņkārīgiem iesācējiem un māksliniekiem ar pieredzi.", seeClasses:"Skatīt nodarbības", privateTitle:"Nodarbība, kas veidota tev", privateBody:"Piesaki individuālu zīmēšanas vai gleznošanas nodarbību manā Rīgas studijā.", book:"Pieteikt privāto nodarbību", available:"vietas pieejamas", reserve:"Rezervēt vietu", sold:"Pārdots", add:"Pievienot grozam", shipping:"Piegāde tiek aprēķināta apmaksas laikā", home:"Sākums", contact:"Kontakti", checkout:"Apmaksa", schedule:"Izvēlies laiku", introShop:"Oriģināldarbi", introClasses:"Nodarbības studijā", introPrivate:"Privātās nodarbības", invoice:"Nepieciešams uzņēmuma/PVN rēķins", fullPayment:"Pilna apmaksa rezervē vietu. Atcel 24+ stundas iepriekš, lai saņemtu automātisku atmaksu.", name:"Vārds", email:"E-pasts", message:"Ziņa", selectSlot:"Izvēlies nodarbību", proceed:"Turpināt uz drošu apmaksu" }
};
