"use client";
import { useEffect, useState } from "react";
import { artwork } from "@/lib/catalog";

const money = new Intl.NumberFormat("en-IE", {style:"currency",currency:"EUR",maximumFractionDigits:0});

export default function ShopPage(){
  const [cart,setCart]=useState([]), [active,setActive]=useState(null), [drawer,setDrawer]=useState(false), [invoice,setInvoice]=useState(false), [status,setStatus]=useState(""), [availableIds,setAvailableIds]=useState(null), [liveArtwork,setLiveArtwork]=useState(null);
  useEffect(()=>{fetch("/api/catalog").then(response=>response.ok?response.json():null).then(data=>{if(data?.availableIds)setAvailableIds(data.availableIds);if(data?.artworks)setLiveArtwork(data.artworks)}).catch(()=>{})},[]);
  const visibleArtwork=liveArtwork??(availableIds===null?artwork:artwork.filter(piece=>availableIds.includes(piece.id)));
  const add=(piece)=>{setCart(current=>current.some(item=>item.id===piece.id)?current:[...current,piece]);setDrawer(true)};
  const checkout=async()=>{setStatus("Opening secure checkout…");try{const res=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"art",items:cart,invoice})});const data=await res.json();if(data.url)window.location.href=data.url;else setStatus(data.error||"Checkout is not configured yet.")}catch{setStatus("Checkout could not be reached. Please try again.")}};
  return <main className="shop-page">
    <header className="shop-header"><a href="/">SANDRA RUDZĪTE</a><nav><a href="/portfolio">PORTFOLIO</a><a className="active" href="/shop">SHOP ORIGINALS</a><a href="/inspire">INSPIRE ART STUDIO</a><a href="/contact">CONTACT</a><button onClick={()=>setDrawer(true)}>BAG <b>{cart.length}</b></button></nav></header>
    <section className="shop-intro"><p>ONE-OF-ONE · ORIGINAL PAINTINGS</p><h1>Available<br/><em>works.</em></h1><div><span>Every painting is an original. Shipping is calculated at checkout.</span><span>RIGA, LATVIA · EUR</span></div></section>
    <section className="shop-grid">{visibleArtwork.length?visibleArtwork.map(piece=><article key={piece.id}><button className="shop-image" onClick={()=>setActive(piece)}><img src={piece.image} alt={piece.title}/><span>VIEW WORK →</span></button><div className="shop-card-info"><div><h2>{piece.title}</h2><p>{piece.medium} · {piece.size}</p></div><b>{money.format(piece.price)}</b></div><button className="shop-add" onClick={()=>add(piece)}>ADD TO BAG <span>+</span></button></article>):<div className="shop-sold-out"><h2>All current works are in new homes.</h2><p>Join the studio mailing list or write directly to hear about the next release.</p><a href="/contact">CONTACT SANDRA →</a></div>}</section>
    <section className="shop-note"><p>INTERESTED IN A WORK?</p><h2>For exhibition, collection or shipping questions, write directly to the artist.</h2><a href="/contact">CONTACT SANDRA →</a></section>
    {active&&<div className="shop-dialog" role="dialog" aria-modal="true" onMouseDown={()=>setActive(null)}><button className="shop-close" onClick={()=>setActive(null)}>×</button><div className="shop-dialog-content" onMouseDown={event=>event.stopPropagation()}><img src={active.image} alt={active.title}/><aside><p>ORIGINAL PAINTING</p><h2>{active.title}</h2><b>{money.format(active.price)}</b><span>{active.medium}<br/>{active.size}</span><p className="shop-description">{active.description}</p><button className="shop-add" onClick={()=>{add(active);setActive(null)}}>ADD TO BAG <span>+</span></button></aside></div></div>}
    {drawer&&<div className="shop-drawer-backdrop" onMouseDown={()=>setDrawer(false)}><aside className="shop-drawer" onMouseDown={event=>event.stopPropagation()}><button className="shop-close" onClick={()=>setDrawer(false)}>×</button><p>YOUR BAG · {cart.length} {cart.length===1?"WORK":"WORKS"}</p>{cart.length?<><div className="shop-line-items">{cart.map(piece=><div key={piece.id}><img src={piece.image} alt=""/><span>{piece.title}<small>{piece.medium}</small></span><b>{money.format(piece.price)}</b><button onClick={()=>setCart(current=>current.filter(item=>item.id!==piece.id))}>REMOVE</button></div>)}</div><label className="shop-invoice"><input type="checkbox" checked={invoice} onChange={event=>setInvoice(event.target.checked)}/> I need a business / VAT invoice</label><button className="shop-checkout" onClick={checkout}>CONTINUE TO CHECKOUT →</button><small className="shop-status">{status}</small></>:<div className="shop-empty"><h2>Your bag is empty.</h2><button onClick={()=>setDrawer(false)}>CONTINUE BROWSING →</button></div>}</aside></div>}
  </main>
}
